### ISSUE TITLE
where is project seldon-deploy 

### ISSUE THREAD

**Issue by wangqiaoshi** [SeldonIO/seldon-deploy-docs#108]
hello ,I'm trying to deploy seldon-deploy,i cannot docker pull seldonio/seldon-deploy:0.5.1

and i cannnot  find project seldon-deploy

**Comment by RafalSkolasinski** [comment]
@wangqiaoshi Seldon Deploy is the enterprise product that you can obtain by contacting Seldon as in documentation https://deploy-v0-5.seldon.io/docs/getting-started/

On the main website https://www.seldon.io/ you can also fill in a form to request demo :)
